// This file will be generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/lib/types/database.types.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          role: 'user' | 'admin'
          avatar_url: string | null
          display_name: string | null
          bio: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          role?: 'user' | 'admin'
          avatar_url?: string | null
          display_name?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          role?: 'user' | 'admin'
          avatar_url?: string | null
          display_name?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      guestbook: {
        Row: {
          id: string
          user_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          content: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          content?: string
          created_at?: string
        }
      }
      time_capsule: {
        Row: {
          id: string
          title: string
          content: string
          image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          content: string
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          content?: string
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      skills: {
        Row: {
          id: string
          name: string
          category: string
          proficiency: number
          description: string | null
          icon_url: string | null
          parent_id: string | null
          position_x: number | null
          position_y: number | null
          position_z: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          category: string
          proficiency: number
          description?: string | null
          icon_url?: string | null
          parent_id?: string | null
          position_x?: number | null
          position_y?: number | null
          position_z?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          category?: string
          proficiency?: number
          description?: string | null
          icon_url?: string | null
          parent_id?: string | null
          position_x?: number | null
          position_y?: number | null
          position_z?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          title: string
          description: string
          content: string
          thumbnail_url: string
          tags: string[]
          github_url: string | null
          demo_url: string | null
          published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          content: string
          thumbnail_url: string
          tags?: string[]
          github_url?: string | null
          demo_url?: string | null
          published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          content?: string
          thumbnail_url?: string
          tags?: string[]
          github_url?: string | null
          demo_url?: string | null
          published?: boolean
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}
